name: fake_news
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libcxx=20.1.8
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openssl=3.0.18
  - pandas=2.3.3
  - pip=25.2
  - python=3.13.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - alphashape==1.3.1
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - brotli==1.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - click-log==0.4.0
      - crawl4ai==0.7.6
      - cryptography==46.0.3
      - cssselect==1.3.0
      - distro==1.9.0
      - fake-http-header==0.3.5
      - fake-useragent==2.2.0
      - fastuuid==0.14.0
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - greenlet==3.2.4
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanize==4.14.0
      - hyperframe==6.1.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.3.0
      - litellm==1.78.7
      - lxml==5.4.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - multidict==6.7.0
      - networkx==3.5
      - nltk==3.9.2
      - openai==2.6.1
      - packaging==25.0
      - patchright==1.55.2
      - pillow==12.0.0
      - playwright==1.55.0
      - propcache==0.4.1
      - psutil==7.1.2
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyee==13.0.0
      - pygments==2.19.2
      - pyopenssl==25.3.0
      - python-dotenv==1.1.1
      - pyyaml==6.0.3
      - rank-bm25==0.2.2
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.28.0
      - rtree==1.4.1
      - safetensors==0.6.2
      - scipy==1.16.2
      - shapely==2.1.2
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.8
      - tf-playwright-stealth==1.2.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - trimesh==4.9.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /opt/miniconda3/envs/fake_news
